"""empty message

Revision ID: 13e64cb7fce0
Revises: 65003b9e4a30
Create Date: 2020-05-13 18:41:58.444156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e64cb7fce0'
down_revision = '65003b9e4a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('latitude', sa.String(length=256), nullable=True))
    op.add_column('merchants', sa.Column('longitude', sa.String(length=256), nullable=True))
    op.drop_column('merchants', 'lat_long')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('lat_long', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('merchants', 'longitude')
    op.drop_column('merchants', 'latitude')
    # ### end Alembic commands ###
