"""empty message

Revision ID: 1a8545114b99
Revises: 5dde4e71ddc8
Create Date: 2020-05-16 15:46:15.853951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8545114b99'
down_revision = '5dde4e71ddc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'sub_category_id')
    # ### end Alembic commands ###
