"""empty message

Revision ID: 5dde4e71ddc8
Revises: cdd92febc4ee
Create Date: 2020-05-15 19:20:26.975440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dde4e71ddc8'
down_revision = 'cdd92febc4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_unit', sa.String(length=256), nullable=True))
    op.drop_column('items', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('items', 'item_unit')
    # ### end Alembic commands ###
