"""empty message

Revision ID: 9fcf205c8052
Revises: 407d61c9be39
Create Date: 2020-05-15 17:13:17.858588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd92febc4ee'
down_revision = '407d61c9be39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_merchant_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'merchant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('merchant_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_merchant_id_fkey', 'items', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###
