"""empty message

Revision ID: ef876f649f00
Revises: 6014407ec4ff
Create Date: 2020-06-18 13:45:28.823738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef876f649f00'
down_revision = '6014407ec4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('no_of_items', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'no_of_items')
    # ### end Alembic commands ###
