"""empty message

Revision ID: f4d4dba3f475
Revises: 13e64cb7fce0
Create Date: 2020-05-13 22:04:48.502660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d4dba3f475'
down_revision = '13e64cb7fce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'address')
    op.drop_column('merchants', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
